FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.env .env

# Copy dist của product.api
COPY --from=builder /app/dist/apps/product.api/ ./dist

EXPOSE 3001
CMD ["node", "dist/main.js"]