services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d testdatabase"]
      interval: 10s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
  api:
    build:
      args:
        DATABASE_HOST: postgres
        NODE_ENV: development
    container_name: nestjs_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - db_network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: my_postgres
networks:
  db_network:
    driver: bridge
volumes:
  postgres_data: