# Sử dụng Maven để build
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

# Clone repo
RUN git clone https://github.com/nexiles/keycloak-client-role-attribute-mapper.git .

# Build dự án với Maven
RUN mvn clean install


CMD tail -f /dev/null

#docker build -t keycloak-extension-builder -f Dockerfile.ext.KC .
#docker run -d --name my-builder keycloak-extension-builder