services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d testdatabase"]
      interval: 10s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
      
  # api:
  #   build:
  #     args:
  #       DATABASE_HOST: postgres
  #       NODE_ENV: development
  #   container_name: nestjs_api
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - db_network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_HOST: my_postgres
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://my_postgres:5432/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: dev@1234
      JAVA_OPTS: -Dkeycloak.profile=preview
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    command:
      - start-dev
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
    networks:
      - db_network
  Redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
volumes:
  postgres_data: